declare namespace NodeJS {
  interface ProcessEnv {
    BRIGHTDATA_ENABLED?: string;
    BRIGHTDATA_API_TOKEN?: string;
    BRIGHTDATA_LINKEDIN_PROFILE_SCRAPER_ID?: string;
    BRIGHTDATA_LINKEDIN_COMPANY_SCRAPER_ID?: string;
    BRIGHTDATA_LINKEDIN_JOBS_SCRAPER_ID?: string;
    BRIGHTDATA_GENERIC_JOB_SCRAPER_ID?: string;
    BRIGHTDATA_UNLOCKER_ZONE?: string;
    BRIGHTDATA_UNLOCKER_ENDPOINT?: string;
    BRIGHTDATA_SCRAPER_TRIGGER_URL?: string;
    BRIGHTDATA_SCRAPER_RESULTS_URL?: string;
    BRIGHTDATA_MAX_POLL_MS?: string;
    BRIGHTDATA_POLL_INTERVAL_MS?: string;
  }
}

