[build]
builder = "nixpacks"
buildCommand = "npm ci --only=production && npm run build:production"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
startCommand = "npm start"

[environments.production.variables]
NODE_ENV = "production"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
