[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
startCommand = "npm start"

[environments.production.variables]
NODE_ENV = "production"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
