export const TASK_TABS = [
  { key: 'assigned_to_me', label: 'Assigned to Me' },
  { key: 'assigned_by_me', label: 'Assigned by Me' },
  { key: 'all_team', label: 'All Team Tasks' },
  { key: 'overdue', label: 'Overdue' },
  { key: 'completed', label: 'Completed' },
];

export const MOCK_TASKS = [
  {
    id: 'task-1',
    code: 'TASK-1024',
    title: 'Finalize offer for Sr. Backend Dev',
    status: 'In Review',
    statusTone: 'yellow',
    dueLabel: 'Yesterday',
    dueSort: -1,
    dueOverdue: true,
    priority: 'High',
    priorityTone: 'red',
    commentCount: 3,
    relatedLabel: 'Alex Chen',
    relatedTypeIcon: 'fa-solid fa-user-tie',
    ownerAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-2.jpg',
    assigneeName: 'Mike Ross',
    assigneeAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-2.jpg',
    createdAt: 'Created Oct 10',
    description:
      "Need final sign-off before extending the offer. Confirm compensation band and start date with leadership.",
    assignedToMe: true,
    assignedByMe: false,
    completed: false,
  },
  {
    id: 'task-2',
    code: 'TASK-1025',
    title: 'Schedule debrief with Engineering Lead',
    status: 'In Progress',
    statusTone: 'blue',
    dueLabel: 'Today, 2:00 PM',
    dueSort: 0,
    dueOverdue: false,
    priority: 'Medium',
    priorityTone: 'orange',
    commentCount: 1,
    relatedLabel: 'Backend Role',
    relatedTypeIcon: 'fa-solid fa-briefcase',
    ownerAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg',
    assigneeName: 'Sarah Johnson',
    assigneeAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg',
    createdAt: 'Created Oct 10',
    description:
      "Need to sync with Mike about Alex's technical assessment. Specifically discuss the system design portion and cultural fit notes.",
    assignedToMe: true,
    assignedByMe: true,
    completed: false,
    selected: true,
  },
  {
    id: 'task-3',
    code: 'TASK-1026',
    title: 'Update job description for PM role',
    status: 'To Do',
    statusTone: 'gray',
    dueLabel: 'Tomorrow',
    dueSort: 1,
    dueOverdue: false,
    priority: 'Low',
    priorityTone: 'blue',
    commentCount: 0,
    relatedLabel: 'PM Role #204',
    relatedTypeIcon: 'fa-solid fa-file-contract',
    ownerAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-3.jpg',
    assigneeName: 'Taylor Reed',
    assigneeAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-3.jpg',
    createdAt: 'Created Oct 11',
    description: 'Refresh responsibilities and preferred qualifications before relaunching this role.',
    assignedToMe: false,
    assignedByMe: true,
    completed: false,
  },
  {
    id: 'task-4',
    code: 'TASK-1027',
    title: 'Screen 5 candidates for Design Lead',
    status: 'To Do',
    statusTone: 'gray',
    dueLabel: 'Oct 24, 2024',
    dueSort: 3,
    dueOverdue: false,
    priority: 'Medium',
    priorityTone: 'orange',
    commentCount: 2,
    relatedLabel: 'Design Lead',
    relatedTypeIcon: 'fa-solid fa-briefcase',
    ownerAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg',
    assigneeName: 'Sarah Johnson',
    assigneeAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg',
    createdAt: 'Created Oct 09',
    description: 'Review priority applicants and prepare shortlist before stakeholder sync.',
    assignedToMe: true,
    assignedByMe: false,
    completed: false,
  },
  {
    id: 'task-5',
    code: 'TASK-1028',
    title: 'Send rejection email to candidate #442',
    status: 'Done',
    statusTone: 'green',
    dueLabel: 'Oct 10, 2024',
    dueSort: 5,
    dueOverdue: false,
    priority: 'Low',
    priorityTone: 'blue',
    commentCount: 0,
    relatedLabel: 'Sarah M.',
    relatedTypeIcon: 'fa-solid fa-user',
    ownerAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg',
    assigneeName: 'Sarah Johnson',
    assigneeAvatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg',
    createdAt: 'Created Oct 08',
    description: 'Confirm message template and close the loop with candidate.',
    assignedToMe: true,
    assignedByMe: true,
    completed: true,
  },
];

export const MOCK_ACTIVITY = [
  {
    id: 'activity-1',
    type: 'system',
    author: 'System',
    at: 'Oct 10, 9:00 AM',
    body: 'Task created from Interview Notes',
  },
  {
    id: 'activity-2',
    type: 'comment',
    author: 'Mike Ross',
    at: 'Oct 10, 10:30 AM',
    avatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-2.jpg',
    body: "I'm free at 2pm today. Let's lock it in. @Sarah Johnson can you send the invite?",
  },
  {
    id: 'activity-3',
    type: 'comment-primary',
    author: 'Sarah Johnson',
    at: 'Just now',
    avatar: 'https://storage.googleapis.com/uxpilot-auth.appspot.com/avatars/avatar-1.jpg',
    body: 'Done. Invite sent for 2pm. See you then.',
  },
];
